# Generated by Django 3.0.5 on 2020-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageApp',
            fields=[
                ('id', models.CharField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5, verbose_name='小语种')),
                ('total_name', models.CharField(max_length=256, verbose_name='中文名称')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名称')),
                ('size', models.IntegerField(verbose_name='词条数量')),
                ('create_time', models.DateTimeField(verbose_name='创建时间', auto_now_add=True)),
                ('update_time', models.DateTimeField(verbose_name='更新时间', auto_now_add=True)),
                ],
            options={
                'verbose_name': '语言包',
                'verbose_name_plural': '语言包管理',
            },
        ),
    ]
